name: umacapture
description: Application for the game Umamusume players.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.2

environment:
  sdk: ">=2.17.6"

dependencies:
  flutter:
    sdk: flutter

  another_xlider: ^1.1.2
  archive: ^3.3.1
  audioplayers: ^1.0.1
  auto_route: ^4.2.1
  badges: ^2.0.3
  charset: ^1.0.1
  collection: ^1.16.0
  csv: ^5.0.1
  dart_json_mapper: ^2.2.4+2
  dio: ^4.0.6
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  extended_image: ^6.2.1
  file_picker: ^4.6.1
  flex_color_scheme: ^5.1.0
  flutter_native_splash: ^2.2.5
  flutter_riverpod: ^1.0.4
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^3.2.0
  intl: ^0.17.0
  logger: ^1.1.0
  package_info_plus: ^1.4.2
  pasteboard: ^0.2.0
  path: ^1.8.1
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  pluto_grid: ^5.0.4
  quiver: ^3.1.0
  recase: ^4.0.0
  state_notifier: ^0.7.2+1
  tuple: ^2.0.0
  uuid: ^3.0.6
  window_manager: ^0.2.5


dev_dependencies:
  #  flutter_test:
  #    sdk: flutter

  auto_route_generator: ^4.2.0
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_oss_licenses: ^2.0.1
  hive_generator: ^1.1.3
  msix: ^3.6.2


flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - assets/config/chara_detail/
    - assets/sound/
    - assets/translations/
    - assets/image/
