import 'dart:async';
import 'dart:convert';

import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:window_manager/window_manager.dart';

import '/const.dart';
import '/src/core/bootstrap.dart';
import '/src/core/localization_util.dart';
import '/src/core/raw_frame_probe.dart';
import '/src/core/sentry_util.dart';
import 'src/core/mapper_init.dart';
import 'src/gui/app_widget.dart';
import 'src/preference/storage_box.dart';
import 'src/preference/window_state.dart';

/// Asset holding the generated web license disclosure.
const String webLicenseInfoAsset = "assets/web_license_info.json";

/// Reads [webLicenseInfoAsset], or a `not_provisioned` stand-in when it cannot be read.
///
/// `assets/` is declared as a *directory* asset, so a build produced after a failed codegen
/// run -- which deletes the artifact rather than writing a half-verified one -- still
/// succeeds and only breaks here. A missing artifact means exactly what an unprovisioned
/// one means (nothing was verified), so it travels the same path instead of surfacing as a
/// raw "Unable to load asset" error from the bundle.
Future<Map<String, dynamic>> loadWebLicenseInfo() async {
  try {
    return jsonDecode(await rootBundle.loadString(webLicenseInfoAsset)) as Map<String, dynamic>;
  } catch (error) {
    return {"status": "not_provisioned", "entries": const [], "load_error": "$error"};
  }
}

/// Asset holding the generated disclosure of the components a native build carries.
const String nativeLicenseInfoAsset = "assets/additional_license_info.json";

/// Name [platformDisclosures] matches an entry's `platforms` field against.
///
/// The two builds do not carry the same third-party components -- the desktop installer
/// ships `opencv_world*.dll` and the LGPL FFmpeg videoio plugin next to the executable,
/// while web reaches the same recognition core as Wasm and ships neither -- so which build
/// an entry belongs to is recorded *in the generated index*, by
/// `DistributionInfoBuilder._desktopDisclosures`. Reading it back is the whole platform
/// decision; nothing here re-derives the split from a list of package names.
String get currentLicensePlatform => kIsWeb ? "web" : "windows";

/// The disclosure entries this build has to show, from both generated indexes.
///
/// [webEntries] carry no `platforms` field because every one of them describes a file under
/// `web/` or a component linked into `web/wasm/umacapture_core.wasm`: they exist only on web
/// by construction, which is why they are taken wholesale or not at all.
@visibleForTesting
List<Map<String, dynamic>> platformDisclosures({
  required List<Map<String, dynamic>> nativeEntries,
  required List<Map<String, dynamic>> webEntries,
  required String platform,
}) => [
  for (final entry in nativeEntries)
    if ((entry["platforms"] as List).contains(platform)) entry,
  if (platform == "web") ...webEntries,
];

/// Registers the license texts [LicenseRegistry] cannot discover on its own.
///
/// Two indexes feed it. [nativeLicenseInfoAsset] is generated from the prebuilt and vendored
/// native dependencies and from the DLL list in `windows/runner/CMakeLists.txt`;
/// [webLicenseInfoAsset] is generated by `DistributionInfoBuilder` from `tool/web_deps.json`
/// and covers everything this repository places under `web/`, including the components
/// statically linked into the Wasm recognition core.
///
/// The web index is *verified* on every platform but *disclosed* only on web -- see the
/// comment on [platformDisclosures] above for why the desktop build must not advertise it.
///
/// Throws [StateError] when a release web build carries an unverified web disclosure:
/// such a build would publish third-party code whose licensing was never checked, so it
/// must not start. Every other platform and mode only warns, because a Windows-only
/// checkout legitimately never provisions the web assets.
Future<void> setupLicense() async {
  final nativeInfo = jsonDecode(await rootBundle.loadString(nativeLicenseInfoAsset)) as Map<String, dynamic>;
  final webInfo = await loadWebLicenseInfo();

  if (webInfo["status"] != "verified") {
    final reason = webInfo["load_error"] == null
        ? "it is '${webInfo["status"]}', not 'verified'"
        : "it could not be read (${webInfo["load_error"]})";
    final message =
        "$webLicenseInfoAsset: $reason. The web license disclosure is incomplete, so this "
        "build must not publish the web assets. Provision web/ (uv run tool/fetch_web_deps.py) "
        "and re-run 'dart run build_runner build --force-jit'.";
    if (kIsWeb && kReleaseMode) {
      throw StateError(message);
    }
    debugPrint(message);
  }

  // `assets/` is declared as a *directory* asset, so both generated disclosures are bundled
  // into every build -- the Windows installer carries the web index and a web build carries the
  // native one. Disclosing either wholesale makes the licence page claim components the build
  // does not have (mediabunny, the Emscripten runtime, musl and the LLVM runtimes on Windows;
  // the OpenCV DLLs and the FFmpeg videoio plugin on web), which is over-disclosure: legally
  // harmless, factually wrong, and unreadable for anyone auditing what this build actually
  // ships. So both artifacts are still READ everywhere (the verification above is a
  // developer-facing check a Windows-only checkout should also see) and only the entries this
  // platform carries are DISCLOSED.
  final selected = platformDisclosures(
    nativeEntries: (nativeInfo["entries"] as List).cast<Map<String, dynamic>>(),
    webEntries: (webInfo["entries"] as List).cast<Map<String, dynamic>>(),
    platform: currentLicensePlatform,
  );

  // The license page groups entries by package name, and one license text can be claimed by
  // more than one entry (a sub-notice such as {fmt} under spdlog, or a component both indexes
  // reach). Grouping by license-asset path yields each text once with every notice that points
  // at it, rather than repeating the text under the same package. The provenance lines are what
  // distinguish the claims, so none of them is dropped.
  final byAsset = <String, List<Map<String, dynamic>>>{};
  for (final entry in selected) {
    byAsset.putIfAbsent(entry["asset"] as String, () => []).add(entry);
  }

  LicenseRegistry.addLicense(() async* {
    for (final group in byAsset.entries) {
      final text = await rootBundle.loadString(group.key);
      final packages = <String>{for (final entry in group.value) entry["package"] as String};
      final notices = [
        for (final entry in group.value)
          if ((entry["notice"] as String?)?.isNotEmpty ?? false) entry["notice"] as String,
      ];
      yield LicenseEntryWithLineBreaks(packages.toList(), [...notices, text].join("\n\n"));
    }
  });
}

/// Paints [message] and logs it, after a startup check refused to let the app run.
///
/// This runs before `runWithSentry`, so letting the error propagate would reach the browser
/// as an unhandled exception with nothing painted -- a blank page with no console entry that
/// points at the cause. Painting the reason (and printing it, which reaches the browser
/// console) is what makes the refusal visible instead of looking like a broken deployment.
void reportFatalStartupError(String message) {
  debugPrint("umacapture: startup aborted -- $message");
  runApp(_StartupFailureApp(message: message));
}

/// One named step of the startup sequence.
///
/// The name is read as the tail of "startup failed while ...", so it is written as a gerund
/// phrase describing what the step was doing.
typedef StartupStep = (String, Future<void> Function());

/// The startup sequence, as named steps, in the order they have to run.
///
/// **Everything `main()` does between the binding and `runApp` is here**, including the
/// synchronous initialisers: a step that stays outside the list is a step whose failure is
/// assumed impossible, and that assumption is what this list exists to stop anyone making
/// silently. (The binding itself cannot be a step -- the refusal screen needs it.)
///
/// Building the list is free -- nothing here runs until [runStartupSequence] awaits it -- so
/// a test can read the sequence without booting the app.
@visibleForTesting
List<StartupStep> startupSteps() {
  // Resolve the user-configured data root before opening Hive: the settings database
  // itself is relocatable, so its location cannot be stored inside it.
  String? dataRoot;
  return [
    // First, and before anything is awaited: the browser location is rewritten as the app
    // navigates, and the launch query would be gone by then.
    ("reading the launch flags", () async => initRawFrameProbeFlag()),
    (
      "configuring the browser context menu",
      () async {
        // web only: let the app's own context menus (flutter_context_menu) show instead of
        // the browser default. No-op on non-web platforms.
        if (kIsWeb) {
          await BrowserContextMenu.disableContextMenu();
        }
      },
    ),
    ("registering the data mappers", () async => initializeMappers()),
    ("reading the configured data root", () async => dataRoot = await readDataRootOverride()),
    ("opening the settings database", () => StorageBox.ensureOpened(reset: false, dataRoot: dataRoot)),
    ("loading the translations", setupLocalization),
    // A release web build with an unverified web license disclosure aborts startup here,
    // before Sentry's app runner swallows it into a "start anyway" path.
    ("setting up the license information", setupLicense),
  ];
}

/// What the refusal screen says when the step named [step] failed with [error].
///
/// A [StateError] is how a step refuses *deliberately* -- the unverified web-disclosure
/// refusal in [setupLicense] is the one that exists today -- and its message is already
/// written for the reader, so it is shown as-is. Anything else is an unexpected failure,
/// where naming the step is the only thing that tells the reader which part of the boot
/// broke.
@visibleForTesting
String startupFailureMessage(String step, Object error) =>
    error is StateError ? error.message : "startup failed while $step: $error";

/// Runs [steps] in order, painting the reason and stopping at the first failure.
///
/// The sequence is *data* rather than a chain of hand-written `try` blocks because the guard
/// has to cover the steps that get added later too. Written by hand it covered only the
/// licence setup, and the Hive open that runs before it still escaped `main()` unhandled --
/// on web that is a permanently blank page with nothing but a console entry, which a visitor
/// cannot tell from a broken deployment. Here the loop, not whoever adds the next step,
/// decides what is covered.
///
/// [onFatal] is injected so a test can read what would be painted without driving `runApp`.
///
/// Returns false when a step failed, i.e. when the application must not start.
@visibleForTesting
Future<bool> runStartupSequence(List<StartupStep> steps, {void Function(String message)? onFatal}) async {
  for (final (name, step) in steps) {
    try {
      await step();
    } catch (error, stackTrace) {
      debugPrint("umacapture: startup step '$name' failed\n$stackTrace");
      (onFatal ?? reportFatalStartupError)(startupFailureMessage(name, error));
      return false;
    }
  }
  return true;
}

/// Minimal, dependency-free screen shown instead of the application.
///
/// Dependency-free is a requirement, not a convenience: this screen has to be able to report
/// the failure of the very step that would have provided its dependencies. So it reads no
/// translation (its text is English on purpose), no app theme and no setting -- only
/// `WidgetsFlutterBinding`, which `main()` initialises before the first step.
class _StartupFailureApp extends StatelessWidget {
  const _StartupFailureApp({required this.message});

  final String message;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SafeArea(
          child: Center(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(24),
              child: Builder(
                builder: (context) {
                  final theme = Theme.of(context);
                  return Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(Icons.error_outline, size: 48, color: theme.colorScheme.error),
                      const SizedBox(height: 16),
                      Text("umacapture could not start", style: theme.textTheme.titleLarge),
                      const SizedBox(height: 12),
                      SelectableText(message, textAlign: TextAlign.center, style: theme.textTheme.bodyMedium),
                    ],
                  );
                },
              ),
            ),
          ),
        ),
      ),
    );
  }
}

void setupWindowManager() async {
  await windowManager.ensureInitialized();
  windowManager.waitUntilReadyToShow(
    const WindowOptions(titleBarStyle: TitleBarStyle.hidden, minimumSize: Size(600, 400), center: true),
    () async {
      final box = WindowStateBox();
      final size = box.getSize();
      if (size != null) {
        await windowManager.setSize(size);
      }

      final offset = box.getOffset();
      if (offset != null) {
        await windowManager.setPosition(offset);
      }

      await windowManager.show();
      await windowManager.focus();

      // The application sometimes starts with a blank white screen.
      // This is probably due to the order of flutter build and windows paint, so force rebuild here.
      Future.delayed(const Duration(milliseconds: 16), () => applicationWidgetRebuildEvent.add(null));
    },
  );
}

void run() {
  runApp(
    ProviderScope(
      // riverpod 3 enables automatic retry (up to 10x with backoff) for any
      // provider that fails with an Exception. Our network loaders rethrow after
      // captureException(), so retrying would emit duplicate Sentry reports and
      // delay the error UI. Disable it globally to keep the riverpod 2 behavior;
      // re-enable selectively if a loader genuinely benefits from retry.
      retry: (retryCount, error) => null,
      // observers: [
      //   if (kDebugMode) ProviderLogger(),
      // ],
      // EasyLocalization must be placed at the root. Otherwise, hot reload will not work for some reason.
      child: EasyLocalization(
        path: "assets/translations",
        useOnlyLangCode: true,
        useFallbackTranslations: true,
        supportedLocales: const [Locale('ja')],
        fallbackLocale: const Locale('ja'),
        child: ApplicationWidget(),
      ),
    ),
  );
}

FutureOr<void> main() async {
  // The only thing that cannot be a startup step: the refusal screen a failed step paints
  // needs the binding, so it has to exist before the first step runs.
  WidgetsFlutterBinding.ensureInitialized();
  // Every startup step goes through here, so a failure in any of them -- not just the
  // licence one -- paints its reason instead of leaving a blank page.
  if (!await runStartupSequence(startupSteps())) {
    return;
  }
  if (CurrentPlatform.hasWindowFrame()) {
    // Deliberately not a startup step: its work finishes in `waitUntilReadyToShow`, whose
    // callback the engine only invokes once the app is painting, so it has to be running
    // alongside `runApp` rather than before it. Which also means a failure here costs the
    // saved window geometry, not the blank page the sequence exists to prevent.
    setupWindowManager();
  }
  runWithSentry(run);
}
